language: python
sudo: false

notifications:
  slack:
    on_success: never
    on_failure: never
  email:
    on_success: never # default: change
    on_failure: never # default: always
cache:
  pip: true

env:
  global:
    - DEPS=$HOME/deps
    - PATH=$DEPS/bin:$PATH
  matrix:
    - LINT=vimlint-errors
    - LINT=vimlint
    - LINT=vint-errors
    - LINT=vint
    - LINT=vader

matrix:
  allow_failures:
    - env: LINT=vimlint
    - env: LINT=vint

install: .ci/install.sh
script: .ci/script.sh
after_success: .ci/after_success.sh
# $TRAVIS_TEST_RESULT is the log
after_failure: .ci/after_failure.sh
